[database]
user = {{env "BOOK_CONTROL_SYSTEM_DATABASE_USER"}}
port = {{env "BOOK_CONTROL_SYSTEM_DATABASE_PORT"}}
database = {{env "BOOK_CONTROL_SYSTEM_DATABASE_NAME"}}
password = {{env "BOOK_CONTROL_SYSTEM_DATABASE_PASSWORD"}}
host = {{env "BOOL_CONTROL_SYSTEM_DATABASE_HOST"}}
